import Head from "next/head";
import CategoryBar from "/src/components/CategoryBar";
import Feed from "/src/components/Feed";
import { useState } from "react";

export default function Home() {
  const [selected, setSelected] = useState("latest");

  return (
    <div className="mt-5 sm:mt-20 max-w-2xl mx-auto">
      <Head>
        <title>Long Addition</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/starlogo-192x192.png" />
      </Head>

      <div className="flex">
        <CategoryBar selected={selected} setSelected={setSelected} />
        <Feed selected={selected} />
      </div>
    </div>
  );
}
